### ISSUE TITLE
[11ty] Unhandled rejection in promise: (more in DEBUG output) [11ty] Caching an already local asset is not yet supported. (via Error)

### ISSUE THREAD

**Issue by nlebellier** [LkeMitchll/interroban.gg#26]
Hi,

i wanted to try your code and it fails

```
nvm use 19
Now using node v19.9.0 (npm v9.6.3)
❯ rm -rf node_modules
❯ npm install

added 444 packages, and audited 445 packages in 4s

148 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
❯ npm audit fix

changed 1 package, and audited 445 packages in 2s

148 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
❯ npm run build

> interroban.gg@4.5.0 build
> npx @11ty/eleventy

[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] Caching an already local asset is not yet supported. (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Caching an already local asset is not yet supported.
[11ty]     at save (/home/nlb/code/interroban.gg/node_modules/@11ty/eleventy-fetch/eleventy-fetch.js:39:25)
[11ty]     at /home/nlb/code/interroban.gg/node_modules/@11ty/eleventy-fetch/eleventy-fetch.js:70:10
[11ty]     at run (/home/nlb/code/interroban.gg/node_modules/p-queue/dist/index.js:157:104)
[11ty]     at PQueue._tryToStartAnother (/home/nlb/code/interroban.gg/node_modules/p-queue/dist/index.js:105:17)
[11ty]     at /home/nlb/code/interroban.gg/node_modules/p-queue/dist/index.js:171:18
[11ty]     at new Promise (<anonymous>)
[11ty]     at PQueue.add (/home/nlb/code/interroban.gg/node_modules/p-queue/dist/index.js:152:16)
[11ty]     at queueSave (/home/nlb/code/interroban.gg/node_modules/@11ty/eleventy-fetch/eleventy-fetch.js:59:30)
[11ty]     at module.exports (/home/nlb/code/interroban.gg/node_modules/@11ty/eleventy-fetch/eleventy-fetch.js:69:9)
[11ty]     at BookmarksAPI.fetchPublishedBookmarks (file:///home/nlb/code/interroban.gg/src/_providers/bookmarks.js:9:12)
  │  ~/code/interroban.gg │   main !1 ▓
```

Cheers

**Comment by LkeMitchll** [comment]
@nlebellier I'm not sure why you're seeing this specific error. It looks like it's from the bookmarks provider. I'm guessing its because you don't have a URL set for the bookmarks API, my bookmarks API is currently closed source unfortunately.
